#+TITLE: The Ghost Coders

** Introdução

  Bem vindos ao *the ghost coders.* :brazil:

  :us: __Foreigners, please use translation. I don't know if you will understand it anyway...__

  Este github é mula, feito pra vocês criarem e mexerem no servidor de vocês.

** O que mudou? Por que PT-BR? O que aconteceu?

  Convertemos ele para :brazil: PT-BR, o que quer dizer que a partir da data da modificação deste ORG, tudo que era :us: EN-US estará como legado, salvo ou arquivado apenas para fins de backup.

  Quando foi criada, a conta tinha o objetivo de documentar e disponibilizar ferramentas para desenvolvimento e manuseio/manutenção/gerenciamento do servidor de vocês. Tudo tinha sido feito em inglês, na esperança de obter ajuda da comunidade internacional, cuja qual, muitos não são falantes da língua portuguesa.

  Porém, toda a ajuda que recebemos no tocante a documentação foi ajuda da comunidade brasileira.

** As exceções: os estrangeiros que ajudaram

  Com relação a ajuda estrangeira, há apenas DUAS exceções:
  
  1. Um certo alguém que todos sabem quem é cujo nickname foi pedido para não ser mencionado (e me bloqueou/excluiu no discord ainda kkkk) mas que teve a contribuição MAIS IMPORTANTE para toda a comunidade, parabéns pelo feito, você merece! E obrigado mais uma vez.
  2. Outra pessoa que não mediu esforços na parte de testes de binários (fuçação sem fim nos arquivos). Obrigado pelo seu tempo e pela sua loucura de mexer com os arquivos mais do que se mexe um misturador de tintas xD.

  Ambos franceses.

  Outros até tentaram ajudar, apreciamos sua ajuda mas estão mencionados aqui os que fizeram a maior diferença. É só olhar nos PR: não há nenhum de estrangeiros até a data, e, fora dos PR, a cena mais forte estava no discord.


** Projetos? Ferramentas? Cade?

*Por esses motivos* citados noo artigo do [[https://github.com/theghostcoders/.rantrepo][rant]] acima, projetos novos e ferramentas que forem lançadas podem ser *OU NÃO* open source. Mas que fique claro: não garantimos nada, afinal, se esforçar pra acabar ajudando esses que vivem de se vangloriar, ter o rei na barriga pois seguraram fix por muito tempo, e, agora que a única exclusividade tá na customização dos servidores querem vir sugar conteúdo? Não, obrigado, já tem muita coisa em outros repositórios e se os auto-proclamados Devs do servidor de vocês sabem mesmo desenvolver, poderão se deliciar na documentação ou nos mesmos e criar ferramentas para vocês, caso contrário, é hora de sentar e esperar bastante pelo que pode (ou não) ser lançado.

Até por estar me distanciando um pouco do discord e da cena em geral, os projetos podem demorar a aparecer, minha vontade era de não ajudar mais em nada e ficar ali jogando meu servidorzinho local ou servidores que são 100% f2p, igual fiz em outra cena de jogo private.

* Projetos
  - Essenciais
    + Instalador
    + Documentação completa dos comandos GM (Em progresso, PRs são apreciados)
    + Emulador (Ainda não iniciado)¹
  - Ferramentas para loucos
    + NPC Creator (Em progresso)
    + Gerenciador de Scenes (Em progresso)
    + dvloger
    + ddsconverter
    + SQL Queries (já disponível em: database/sql)
    + Editor de Mapas (Ainda não iniciado)²
    + continua.

¹ - Extremamente importante para a sobrevivência a longo prazo do projeto desse jogo.
² - Diferente do Gerenciador de Scenes, esse é pra editar os mapas (aparência/terrrenos/colisões) do jogo mesmo.

Importante sobre emulador: em 2011 eu tentei começar um emulador de server pirata em delphi pra esse jogo, como em um certo mmorpg flash da ae (que fiz mas abandonei o projeto), mas, esbarrei em pacotes criptografados e após algum estudo foi descoberto que havia criptografia RSA nos mesmos, devido a estar completamente sozinho naquela empreitada eu desisti cedo. Esse recadinho fica pra quem acha que eu nasci ontem ou que acha que tentou primeiro, até pode ter tentado, mas com exceção de 1 pessoa, o restante tentou da maneira mais burra/bunda mole possível... 99% não sabem o básico e não sabiam o que é Linux/Banco de Dados/etc antes desses vazamentos, sinto pena mas não remorso kkk.

=Não esqueça de deixar estrela nos repositórios que você gostar!=

Você pode contribuir com o projeto criando issues, pull requests, e forkando. Claramente, *se for forkar, insira o link do repositório original no seu repo forkado ou referência.*
